### ISSUE TITLE
Header(s) missing from install

### ISSUE THREAD

**Issue by bgranzow** [ibaned/omega_h2#3]
When building from an external build directory, 'make install'
returns the following error:

file INSTALL cannot find "/home/bng/omega_h/build/omega_h.hpp"

because the appropriate header(s) have not been copied to the CMAKE_CURRENT_BINARY_DIR

**Comment by ibaned** [comment]
This was hopefully just addressed by 25e8dac and 9127abf, please confirm.

**Comment by bgranzow** [comment]
This commit did indeed fix the problem.
