### ISSUE TITLE
Provide version info in omega_h-config.cmake

### ISSUE THREAD

**Issue by bgranzow** [ibaned/omega_h2#4]
This might be useful for projects that depend on omega_h and need to require above a certain version?

**Comment by bgranzow** [comment]
Something like adding this line to omega_h-config-in.cmake:
set(Omega_h_VERSION "@OSH_MAJOR@.@OSH_MINOR@.@OSH_PATCH@")
is what I had in mind

**Comment by ibaned** [comment]
Should be addressed by c0aaf2c.
I actually implemented the whole scheme [here](https://cmake.org/Wiki/CMake/Tutorials/Packaging#Package_Version_Files),
which should give you `Omega_h_VERSION` as a byproduct of calling `find_package`,
and `find_package` will only succeed if the versions are compatible. You can also use the `EXACT` argument to get exactly a version. However, this earlier scheme makes the package's CMake file responsible for comparison logic and only outputs "equality with tolerance" essentially. Luckily, later versions of CMake implement `if(<variable|string> VERSION_GREATER <variable|string>)`, so you can use those on Omega_h_VERSION to get what you want.

**Comment by bgranzow** [comment]
As a minor note, this gives you the variable `omega_h_VERSION`, not `Omega_h_VERSION`, since the package name is `omega_h`.

**Comment by ibaned** [comment]
due to CMake's lower-casing when looking for the file, these exported files will actually accept being called either `omega_h` or `Omega_h`. This private repo uses the upper case name and it still works:

https://github.com/ibaned/sms2osh/blob/master/CMakeLists.txt#L4

**Comment by bgranzow** [comment]
OK, I just tried that out and it works. When using find_package to find Omega_h, you have to be consistent, though. If you use `find_package(Omega_h)`, then you get the variable `Omega_h_VERSION`. If you use `find_package(omega_h)`, then you get the variable `omega_h_VERSION`.
